// Root entrypoint: the primary surface of the @insler/platform umbrella —
// fleet (scanner + desired-state model), generator (pluggable codegen), and
// reconciler (plan/diff/apply engine). The subpath entrypoints (./fleet,
// ./generator, ./reconciler) remain the canonical import style and preserve
// ADR-0002's partial-adoption property.

export { buildFleetManifest, discoverServices, scanFleet } from './fleet/index.js';
export type {
  FleetEdge,
  FleetError,
  FleetExpose,
  FleetGraph,
  FleetManifest,
  FleetResult,
  FleetRoute,
  ScannedService,
  ScanOptions,
} from './fleet/index.js';

export {
  autoscalerPlugin,
  cloudRunPlatform,
  createGenerator,
  createSecretBindingPlugin,
  dataStoreClaimsPlugin,
  edgeRoutingPlugin,
  fleetInventoryPlugin,
  kubernetesPlugin,
  natsCredentialsPlugin,
  serverlessPlugin,
} from './generator/index.js';
export type {
  AutoscalerOptions,
  DataStoreClaimsConfig,
  DataStoreTypeDefaults,
  EdgeHttpMethod,
  EdgeRoute,
  EdgeRoutingTable,
  EdgeStreamMode,
  GeneratedFile,
  GeneratedFileFormat,
  GenerationDiff,
  GenerationResult,
  Generator,
  GeneratorOptions,
  GeneratorPlugin,
  GeneratorTarget,
  KubernetesPlugin,
  KubernetesPluginConfig,
  NatsConnectivity,
  ProbeConfig,
  ProvisionPolicy,
  ResourceQuantities,
  ResourceRequirements,
  SecretBindingConfig,
  SecretStoreRef,
  ServerlessConfig,
  ServerlessPlatform,
  ServerlessSecretBinding,
  ServerlessService,
  WorkloadIdentityAnnotation,
} from './generator/index.js';

export {
  applyAuto,
  applyGated,
  blastRadius,
  createControlLoop,
  createMemoryStateProvider,
  createReconciler,
  diffState,
  renderPlan,
  renderPlanComment,
  toResources,
} from './reconciler/index.js';
export type {
  ApplyOptions,
  ApplyResult,
  AuditRecord,
  AuditSink,
  AutoApplyResult,
  BlastRadius,
  ChangeAction,
  ControlLoop,
  ControlLoopMode,
  ControlLoopOptions,
  DriftAction,
  DriftCategory,
  DriftEvent,
  DriftLog,
  DriftLogEntry,
  DriftReport,
  GatedApplyOptions,
  GatedApplyResult,
  MemoryStateProvider,
  Plan,
  PlanSummary,
  Reconciler,
  ReconcileResult,
  Resource,
  ResourceChange,
  SetAppliedOptions,
  StateProvider,
  Ticker,
} from './reconciler/index.js';
